### ISSUE TITLE
Suggestion: Add animations for subscribed threads

### ISSUE THREAD

**Issue by MysteryTopHat** [Mopsgamer/BetterDiscord-codes#1]
Here's a suggestion. When clicking to a new server, let the subscribed threads be animated too like the rest of the channels.  Right now, they just automatically appear. Good work!

**Comment by Mopsgamer** [comment]
You might like the solution to this problem in version 1.0.4.
It is very difficult to animate threads because they are on different levels with channels.
Perhaps this will be implemented later.

**Comment by MysteryTopHat** [comment]
Oh, I understand. Thank you for explaining.
