### ISSUE TITLE
The settings a user sets do not get saved and revert on restart

### ISSUE THREAD

**Issue by scouttiger** [Mopsgamer/BetterDiscord-codes#12]
Whenever I set settings in the menu it doesnt save them. This means that the moment I restart discord, it reverts back to the default settings. Same goes for turning the plugin off and on, that also reverts all the settings back to default.

Greetings

**Comment by asusplayer** [comment]
Hey, just download the file here from Github again. The file hosted by betterdiscord is still on 1.0.6, but the new version is 1.0.7.
File Link: https://github.com/Mopsgamer/BetterDiscord-codes/blob/Animations/Animations.plugin.js

Greetings
