### ISSUE TITLE
After latest update - Not all channels load

### ISSUE THREAD

**Issue by Corard** [Mopsgamer/BetterDiscord-codes#13]
As the title suggests after the latest update, not all channels are loading properly. After scrolling down the channel list, I need to click the server icon again to have the rest of the channels load in. (Screen recording attached)

User lists and chat messages work as expected. I have tried disabling and enabling the plugin, as well as deleting and reinstalling it.

https://user-images.githubusercontent.com/51264981/148648695-7981fd40-cfcc-4834-a0b6-6dc5b11682b4.mp4

**Comment by keatit71** [comment]
having the same issue, channels loaded after disabling the plugin

**Comment by Mopsgamer** [comment]
Try the new version 1.1.1, it should fix this.
