### ISSUE TITLE
Minimising and maximizing a channel group doesn't load the channels

### ISSUE THREAD

**Issue by Happylama25** [Mopsgamer/BetterDiscord-codes#14]
When minimizing a server group and then maximizing it, the channels don't load in until clicking the server icon or changing to another channel, noticed it happening on v1.1.0 and updated to v1.1.1 with the same issue. Might be related to #13 

https://user-images.githubusercontent.com/49815691/148665248-56b1c39f-d067-422f-8d87-4db92009feb2.mp4

.

**Comment by Yilmaz4** [comment]
Same for me
![image](https://user-images.githubusercontent.com/77583632/148673833-07c881a8-ca1e-43b9-a852-11f588145441.png)

**Comment by Mopsgamer** [comment]
v1.1.2
