### ISSUE TITLE
Animations causing channels to not show up

### ISSUE THREAD

**Issue by Zalnor** [Mopsgamer/BetterDiscord-codes#15]
When in servers with many channels scrolling up or down to far causes channels to just vanish or not show up, this also happens with expanding channel groups.
[Normal Discord](https://i.imgur.com/ahjEPX5.png)
[With Animations](https://i.imgur.com/FtuilOM.png)

**Comment by Mopsgamer** [comment]
BetterDiscord is behind on new versions. Update the plugin to v1.1.3. If your version is the latest, but this problem has not disappeared, report it again.
