### ISSUE TITLE
Animations no longer play due to Discord update

### ISSUE THREAD

**Issue by darkpixlz** [Mopsgamer/BetterDiscord-codes#18]

**Comment by Mopsgamer** [comment]
Wait for the new version (1.1.8.4) to be approved.

**Comment by KeparYTbcc** [comment]
rip, wut i tought

**Comment by Mopsgamer** [comment]
Patience...

For now you can download the working version [here](https://downgit.evecalm.com/#/home?url=https://github.com/Mopsgamer/BetterDiscord-codes/tree/main/plugins/Animations/Animations.plugin.js).
