### ISSUE TITLE
Using Animations with HorizontalServerList

### ISSUE THREAD

**Issue by 9xKiritox6** [Mopsgamer/BetterDiscord-codes#19]
Starting v1.2.0 and Above (which is the Current Version 1.2.3), when Animations plugins are being used with HorizontalServerList, The Server Icons Are Tilted 90

v1.1.8.5
![image](https://user-images.githubusercontent.com/81343761/150950104-5e98be1a-bce7-4ac2-b330-c92e07612ead.png)

v1.2.0
![image](https://user-images.githubusercontent.com/81343761/150950537-ff70e316-8083-4f22-826a-a19b9f1d03ce.png)

(Current) v1.2.3

![image](https://user-images.githubusercontent.com/81343761/150951306-c83f2d0e-d139-4eb2-a16d-572b44e1ea2d.png)

**Comment by Mopsgamer** [comment]
https://betterdiscord.app/theme/Horizontal%20Server%20List

**Comment by joker-119** [comment]
![image](https://user-images.githubusercontent.com/10914157/159166250-d8458e2b-36ba-4470-9834-ae19efe34311.png)
This is what happens now, HorizontalServerList v. 2.10 Animations v. 1.3.3

**Comment by 9xKiritox6** [comment]
Another Bug Occured... Starting v1.3.3 (which is the Current Version), when Animations plugins are being used with HorizontalServerList, The Entire Server Selection is Missing

![image](https://user-images.githubusercontent.com/81343761/159166673-8006a347-a600-45d4-940a-e5cf235d14b5.png)

**Comment by Mopsgamer** [comment]
1.3.4 should fix it.

**Comment by joker-119** [comment]
Confirmed fixed in 1.3.4, tyvm
