### ISSUE TITLE
Suggestion: Add an animation to a message before it's sent

### ISSUE THREAD

**Issue by Janekja** [Mopsgamer/BetterDiscord-codes#2]
People with slower internet often see a gray text before it's actually sent. How about adding an option to animate it/hide it?
It'd make a great addition, because it appears for a few seconds without animation before the actual message is sent and animated

**Comment by Mopsgamer** [comment]
Version 1.0.4 should not have this problem. The gray text animation was purposely turned off, because at an average connection speed there was a "glitch" animation effect.

I am monitoring this problem in all its manifestations.
