### ISSUE TITLE
Plugin rotated my servers

### ISSUE THREAD

**Issue by Retardantt** [Mopsgamer/BetterDiscord-codes#20]
Hi, when I turn on this plugin, which is amazing, I love the animations, my servers rotate, I have uploaded an image so u can see it. If you just add a simple toggle, that would choose to rotate servers back it would be nice :)

![image](https://user-images.githubusercontent.com/68786400/151347168-69b4ab83-c646-4753-bab4-274cb496956f.png)

**Comment by Mopsgamer** [comment]
I fixed it a long time ago in version 1.2.5, are you sure?

**Comment by Retardantt** [comment]
I have the newest version

![image](https://user-images.githubusercontent.com/68786400/151352830-67b55985-407f-4ec4-8785-b7e0a92b5404.png)

**Comment by Retardantt** [comment]
Yeah, it was another plugin fault, I just deleted the horizontal server plugin and downloaded another, thx for help :)

![image](https://user-images.githubusercontent.com/68786400/151372988-1936d100-6a9c-4dd6-9a7a-f216d7a6f701.png)
