### ISSUE TITLE
When the channel list is too long...

### ISSUE THREAD

**Issue by johnchun10** [Mopsgamer/BetterDiscord-codes#21]
When there is a bunch of channels in a list, the animations play. However, when you scroll back up, the animation refreshes. I've tried adding the number of animations that play for lists but that doesn't help. This is probably a known problem but im not sure. Here's a pretty bad screen shot but yeah it happens for a split second.
![Screenshot_1](https://user-images.githubusercontent.com/86617913/151455879-f5c5d89a-d520-4869-875e-775e67883fc3.png)

**Comment by Mopsgamer** [comment]
That's fine, I want to fix it.
