### ISSUE TITLE
Embedded Videos lag

### ISSUE THREAD

**Issue by GodsAperture** [Mopsgamer/BetterDiscord-codes#22]
I love the new update (1.2.5) but right when I click on an embedded video, Discord just starts eating resources faster than a super computer. I ended up needing to turn off Animations so that Discord doesn't end up killing itself. I don't know the exact cause of the massive lag on Discord in Animations, only that Animations is the cause.

**Comment by Mopsgamer** [comment]
At what point do lags begin?
Can I see an example?

I don't see any lags anywhere.
