### ISSUE TITLE
Error "Cannot read property 'classList' of undefined"

### ISSUE THREAD

**Issue by Catif** [Mopsgamer/BetterDiscord-codes#26]
With your update 1.2.7, my dev console have a lot of error per second.

In the setting plugin, I delete the class in list : membersGroup-2eiWxl
(Even if I keep the class, the error stay)

The error :
![image](https://user-images.githubusercontent.com/84462178/152644668-3c479c24-36fc-4136-a50f-e2048910a192.png)

**Comment by Mopsgamer** [comment]
I think I fixed this problem in 1.2.7.1

**Comment by Catif** [comment]
I have the same issue with the 1.2.7.1

(Thanks to you for your work !)

**Comment by Mopsgamer** [comment]
I just can't emulate the error, no matter what I do it does not appear.

**Comment by Catif** [comment]
I don't know why, but I don't have the error anymore
