### ISSUE TITLE
The button update, didn't work

### ISSUE THREAD

**Issue by Catif** [Mopsgamer/BetterDiscord-codes#27]
When I have an outdated version of your plugin and I want to update it, I click on "Update" button.

That tell me the new version of the plugin, but when I accept to update. Nothing happened.

**Comment by Mopsgamer** [comment]
There was some problem with the ZLibrary.PluginUpdater.downloadPlugin function. In version 1.2.7.2. Now I manually change the plugin file without re-requests.
