### ISSUE TITLE
[Crash] Could not be constructed?

### ISSUE THREAD

**Issue by RyanCR03** [Mopsgamer/BetterDiscord-codes#30]
![image](https://user-images.githubusercontent.com/32957560/154191015-815042ad-bb37-4c45-ae8e-05628f532a59.png)
```Animations: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306918)
    at Object.loadAddon (<anonymous>:4:268405)
    at Object.loadAddon (<anonymous>:4:305956)
    at FSWatcher.<anonymous> (<anonymous>:4:266254)```

**Comment by Tr3xTheDoctor** [comment]
I'm having the same issue. Reinstalling it doesnt even work

**Comment by palerski** [comment]
Same issue for me

**Comment by Jaeyoon07031** [comment]
The latest BetterDiscord hotfix broke a bunch of plugins, just wait until the developer comes and fixes it. I might take a look at it myself later.

**Comment by Shadow514** [comment]
#32

**Comment by Mopsgamer** [comment]
Can I know what your console says?

**Comment by Shadow514** [comment]
> Can I know what your console says?

Do you mean the popup when the plugin is activated?

**Comment by Mopsgamer** [comment]
> Do you mean the popup that shows saying that something is broken when the plugin is activated?
Console (ctrl+shift+i)

**Comment by keatit71** [comment]
The plugin works fine now.
