### ISSUE TITLE
ROTATE MY SERVERS

### ISSUE THREAD

**Issue by V0LT0** [Mopsgamer/BetterDiscord-codes#34]
WHEN I ENABLED MY SERVERS ROTATE
![Screenshot (281)](https://user-images.githubusercontent.com/99586451/154654397-c7f31c42-33d7-490d-be5a-99698e177ab9.png)

**Comment by V0LT0** [comment]
> same here

i dont know how to fix it

**Comment by Mopsgamer** [comment]
[Attached issue](https://github.com/Mopsgamer/BetterDiscord-codes/issues/19).

You should use this theme
https://betterdiscord.app/theme/Horizontal%20Server%20List
