### ISSUE TITLE
["Plugin to Theme" Bug] Nothing loading when Settings is opened

### ISSUE THREAD

**Issue by Shadow514** [Mopsgamer/BetterDiscord-codes#36]
![abb8e716fc4d1612550182dfc5fa5c0e](https://user-images.githubusercontent.com/93408587/154737792-87b551e2-16f7-47ff-b407-3b042f27c0a8.png)

**Comment by Mopsgamer** [comment]
What exactly are you expecting to load?
I don't see any problems on the screenshot.

**Comment by Mopsgamer** [comment]
-_-
