### ISSUE TITLE
Issue Can't change Duration

### ISSUE THREAD

**Issue by BeamKunGzMARK** [Mopsgamer/BetterDiscord-codes#41]
I have issue can't change a duration on lists

this duration can't change with decimals such as If I want to change to 0.25 It can't.

![image](https://user-images.githubusercontent.com/39422342/156212926-d3fc3ba7-05a3-47b9-b668-918a7f3c767a.png)

**Comment by Mopsgamer** [comment]
1.2.10.2 - update now
