### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by NikitaKaj** [Mopsgamer/BetterDiscord-codes#43]
When the plugin is enabled, the profile color is as if the person is online, even though they are offline.

plugin off
![plugin_off](https://user-images.githubusercontent.com/102430946/163843389-26d88647-373d-4614-95a2-3690ea6d4d34.jpg)

plugin on
![plugin_on](https://user-images.githubusercontent.com/102430946/163843367-2d58b6b1-cf10-44c1-9f6c-868317708e29.jpg)

**Comment by Mopsgamer** [comment]
Someone please confirm that this problem is not in 1.3.5.

**Comment by NikitaKaj** [comment]
Nothing has changed, the bug remains.
