### ISSUE TITLE
Did you already think about adding a smoothness option to Animations?

### ISSUE THREAD

**Issue by Gamesnic** [Mopsgamer/BetterDiscord-codes#44]
Love this plugin because it adds life to Discord. But sometimes the animations feel a bit stiff, from the mostly linear animation.
Could you add a smoothness slider that changes accordingly from Linear to Bezier? That would make it awesome.

Even cooler would be options like Easy Ease, Cubic, Quadratic, exponential, ...

**Comment by Mopsgamer** [comment]
As soon as possible.
