### ISSUE TITLE
Sub menu bug

### ISSUE THREAD

**Issue by SliceTheDuck** [Mopsgamer/BetterDiscord-codes#48]
When using animation any sub menu(from my knowledge only on the profile thingy(screnshot)) doesnt show in the right place/ any location.
1.screenshot: With
2.screenshot: Without
![image](https://user-images.githubusercontent.com/71396941/188457223-2b06244f-abb5-4dbe-9a56-96102e485dba.png)
![image](https://user-images.githubusercontent.com/71396941/188457399-770b3a25-ac9a-4dde-9a53-f75615a086c7.png)

**Comment by Mopsgamer** [comment]
In any case, right now I recommend to disable the animation for popouts.

This bug can appear anywhere, I do not know how to fix it (for now).
Any element can suddenly shift because of the animations.

**Comment by SliceTheDuck** [comment]
Ah ok thank you still
