### ISSUE TITLE
Unable to enable Animations with BD

### ISSUE THREAD

**Issue by sponnify** [Mopsgamer/BetterDiscord-codes#57]
### Plugin

Animations

### Plugin version

v1.3.10

### What is broken?

"Animations could not be started" when trying to enable plugin.

### Client

Stable

### More details

- [ ] I am familiar with JavaScript. I can fix this.

**Comment by Mopsgamer** [comment]
Download the latest version. - Go to the [link](https://raw.githubusercontent.com/Mopsgamer/BetterDiscord-codes/main/plugins/Animations/Animations.plugin.js) and hit `ctrl + s`.
